# HTTP source with prompt variables

GET http://[::1]:55001/test/1

### bar
# @prompt bar
GET http://[::1]:55001/test/2/{{bar}}

### pass
// @prompt pass Password
GET http://[::1]:55001/test/3/{{pass}}
