# Invoke-RestHttp // HTTP // content with variables

// file variables // using later vars is fine
@var2 = {{var1}}
@var1 = 11
@var1 = 42

POST http://[::1]:55001/show?param1={{var2}}
Content-Type: application/json
age: {{var2}}

{
  "version": "{{  version  }}",
  "user": "{{  $dotenv user  }}",
  "randomInt": "{{  $randomInt 0 2  }}",
  "timestamp1": "{{  $timestamp  }}",
  "timestamp2": "{{  $timestamp 1 s  }}",
  "datetimeIso1": "{{  $datetime iso8601  }}",
  "datetimeIso2": "{{  $datetime iso8601 1 s }}",
  "datetimeIso3": "{{  $localDatetime iso8601  }}",
  "datetimeRfc1": "{{  $datetime rfc1123  }}",
  "datetimeRfc2": "{{  $datetime rfc1123 1 s }}",
  "age": {{var2}}
}

### Variable spaces
# outer spaces are trimmed
# PSRest: inner spaces may be single or multiple
# VSCode: some inner spaces must be single, some not
