# Invoke-RestHttp // HTTP // file with expanded variables

// file variables // using later vars is fine
@var2 = {{var1}}
@var1 = 11
@var1 = 42

POST http://127.0.0.1:55000/show?param1={{var2}}
Content-Type: application/json
age: {{var2}}

<@ Basic-3.json
