# Invoke-RestHttp // GraphQL with selected operation name

POST http://[::1]:55001/show
Content-Type: application/json
X-Request-Type: GraphQL
X-GraphQL-Operation: Continents2

< Continents-4.graphql

{
  "regex1": "A",
  "regex2": "N"
}
